# ERI integral evaluation: some tests

In [1]:
from numpy.typing import NDArray
import numpy as np
from py_mods.src.integrals.GTO import generate_angular_momentum_projections
from py_mods.src.integrals.CGTO import create_CGTOClass, Eri_GTO_tensor

In [2]:
# STO3g example:
l = 1
l_tags = ["S", "P", "D", "F", "G", "H"]
l_projs = len(generate_angular_momentum_projections(l))
print(f"There are {l_projs} l_projs")

r1 = np.array([0.0, 0.0, 0.0])
r2 = np.array([0.0, 0.0, 1.4])
H_exps = np.array([1])
H_coeffs = np.array([1])

# Construct the CGTO
H_1s_1 = create_CGTOClass(r1, H_exps, H_coeffs, l)
H_1s_2 = create_CGTOClass(r2, H_exps, H_coeffs, l)
H_1p_1 = create_CGTOClass(r1, H_exps, H_coeffs, l + 1)
H_1p_2 = create_CGTOClass(r2, H_exps, H_coeffs, l + 1)

There are 3 l_projs


In [3]:
print(repr(H_1s_1))
print("\n\n\n")
print(repr(H_1p_1))

CGTOClass(R=array([0., 0., 0.]), exps=array([1]), N_a=np.float64(1.0000000000000002), d_i=array([1]), total_l=1, l_dim=3, l_projections=array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32), primitives=[GTO(R=array([0., 0., 0.]), exp=np.int64(1), total_L=1, l_projections=array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32), normalization_constants=array([1.42541094, 1.42541094, 1.42541094]), charge=1)])




CGTOClass(R=array([0., 0., 0.]), exps=array([1]), N_a=np.float64(1.0), d_i=array([1]), total_l=2, l_dim=6, l_projections=array([[2, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 2, 0],
       [0, 1, 1],
       [0, 0, 2]], dtype=int32), primitives=[GTO(R=array([0., 0., 0.]), exp=np.int64(1), total_L=2, l_projections=array([[2, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 2, 0],
       [0, 1, 1],
       [0, 0, 2]], dtype=int32), normalization_constants=array([1.64592278, 2.85082188, 2.85082188, 1.64592278, 2.85082188,
       1.64592278]), 

In [4]:
Eri_test = Eri_GTO_tensor(H_1s_1, H_1s_1, H_1s_2, H_1s_2)
print(repr(Eri_test))

array([[[[ 0.59314383,  0.        ,  0.        ],
         [ 0.        ,  0.56253372,  0.        ],
         [ 0.        ,  0.        ,  0.64573551]],

        [[ 0.        ,  0.01530505,  0.        ],
         [ 0.01530505,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        , -0.02148479],
         [ 0.        ,  0.        ,  0.        ],
         [-0.02148479,  0.        ,  0.        ]]],


       [[[ 0.        ,  0.01530505,  0.        ],
         [ 0.01530505,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.56253372,  0.        ,  0.        ],
         [ 0.        ,  0.59314383,  0.        ],
         [ 0.        ,  0.        ,  0.64573551]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        , -0.02148479],
         [ 0.        , -0.02148479,  0.        ]]],


       [[[ 0.        ,  0.        , -0.02148479],
         [ 0.        ,  0.        

In [5]:
print(repr(Eri_test))

array([[[[ 0.59314383,  0.        ,  0.        ],
         [ 0.        ,  0.56253372,  0.        ],
         [ 0.        ,  0.        ,  0.64573551]],

        [[ 0.        ,  0.01530505,  0.        ],
         [ 0.01530505,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        , -0.02148479],
         [ 0.        ,  0.        ,  0.        ],
         [-0.02148479,  0.        ,  0.        ]]],


       [[[ 0.        ,  0.01530505,  0.        ],
         [ 0.01530505,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.56253372,  0.        ,  0.        ],
         [ 0.        ,  0.59314383,  0.        ],
         [ 0.        ,  0.        ,  0.64573551]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        , -0.02148479],
         [ 0.        , -0.02148479,  0.        ]]],


       [[[ 0.        ,  0.        , -0.02148479],
         [ 0.        ,  0.        

In [6]:
Eri_test = Eri_GTO_tensor(H_1p_1, H_1s_1, H_1s_2, H_1s_2)
print(repr(Eri_test))

array([[[[ 0.        ,  0.        , -0.05146775],
         [ 0.        ,  0.        ,  0.        ],
         [-0.05146775,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        , -0.01715592],
         [ 0.        , -0.01715592,  0.        ]],

        [[ 0.0807565 ,  0.        ,  0.        ],
         [ 0.        ,  0.06558463,  0.        ],
         [ 0.        ,  0.        ,  0.06976274]]],


       [[[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        , -0.02971492],
         [ 0.        , -0.02971492,  0.        ]],

        [[ 0.        ,  0.        , -0.02971492],
         [ 0.        ,  0.        ,  0.        ],
         [-0.02971492,  0.        ,  0.        ]],

        [[ 0.        ,  0.01313923,  0.        ],
         [ 0.01313923,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]]],


       [[[ 0.13987437,  0.        ,  0.        ],
         [ 0.        ,  0.11359591

In [7]:
Eri_test = Eri_GTO_tensor(H_1p_1, H_1p_1, H_1p_2, H_1p_2)
print(repr(Eri_test))

array([[[[ 0.55398881,  0.        ,  0.        ,  0.17309051,
           0.        ,  0.19830694],
         [ 0.        ,  0.51927153,  0.        ,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.59492081,  0.        ,
           0.        ,  0.        ],
         [ 0.17309051,  0.        ,  0.        ,  0.48896934,
           0.        ,  0.17752182],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.53256545,  0.        ],
         [ 0.19830694,  0.        ,  0.        ,  0.17752182,
           0.        ,  0.5893547 ]],

        [[ 0.        ,  0.02603796,  0.        ,  0.        ,
           0.        ,  0.        ],
         [ 0.02603796,  0.        ,  0.        ,  0.02272664,
           0.        ,  0.01558884],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.02700066,  0.        ],
         [ 0.        ,  0.02272664,  0.        ,  0.        ,
           0.        ,  0.        ],
        

In [8]:
from pyscf import gto
mol = gto.M(
    atom = 'H 0 0 0; H 0 0 1.4;',
    unit = 'Bohr', 
    basis = {'H': gto.basis.parse(f'''
        # This is the standard STO-3G definition
        # Exponent    Contraction Coeff
        H {l_tags[0]}
        3.42525091    0.15432897
    ''')},
    cart=True,
)

mol.build()


overlap = mol.intor('int1e_ovlp')
kin = mol.intor('int1e_kin')
V = mol.intor('int1e_nuc')
ref_eri = mol.intor('int2e')


In [9]:
overlap.shape

(2, 2)

In [10]:
import ctypes as ct
import numpy as np
from numpy.ctypeslib import ndpointer
from py_mods.src.integrals.GTO import GTO

lib = ct.CDLL("/Users/fernando.mata/bin/Oatmeal/notebooks/interest_interface/interest/src/inter_py_lib.so")

lib.interest_prim_py.argtypes = [
    ct.c_double,                                                # factor
    ndpointer(dtype=np.float64, ndim=1, shape=(2**4,)),         # fint_inp

    ct.c_int,                                                   # la_inp
    ct.c_double, ct.c_double, ct.c_double, ct.c_double, ct.c_double,

    ct.c_int,                                                   # lb_inp
    ct.c_double, ct.c_double, ct.c_double, ct.c_double, ct.c_double,

    ct.c_int,                                                   # lc_inp
    ct.c_double, ct.c_double, ct.c_double, ct.c_double, ct.c_double,

    ct.c_int,                                                   # ld_inp
    ct.c_double, ct.c_double, ct.c_double, ct.c_double, ct.c_double,
]
lib.interest_prim_py.restype = None
fint = np.zeros(1000, dtype=np.float64)

def interest_from_gto(gto1:GTO,gto2:GTO,gto3:GTO,gto4:GTO,wroking_array) -> NDArray:
    fact =  1

    la = gto1.total_L
    lb = 1 
    lc = 1 
    ld = 1 

    lib.interest_prim_py(
        fact, full_ao_interest,
        la, 1, 0.0, 0.0, 0.0, 3.42525091,
        lb, 1, 0.0, 0.0, 0.0, 3.42525091,
        lc, 1, 0.0, 0.0, 1.4, 3.42525091,
        ld, 1, 0.0, 0.0, 1.4, 3.42525091,
    )

    return np.array([0])

r1 = np.array([0.0, 0.0, 0.0])
r2 = np.array([0.0, 0.0, 1.4])
r3 = np.array([2.1, 0.0, 0.0])
H_exps = np.array([3.42525091])
H_coeffs = np.array([0.15432897])

# Construct the CGTO
A = create_CGTOClass(r1, H_exps, H_coeffs, 0)
B = create_CGTOClass(r2, H_exps, H_coeffs, 0)
C = create_CGTOClass(r3, H_exps, H_coeffs, 0)

gtos = [A, B, C]

print(repr(gtos))

full_ao = np.zeros([2, 2, 2, 2])
full_ao_interest = np.zeros([2, 2, 2, 2]).flatten()

for i in range(0, 2):
    for j in range(0, 2):
        for k in range(0, 2):
            for l in range(0, 2):

                I = gtos[i]
                J = gtos[j]
                K = gtos[k]
                L = gtos[l]

                full_ao[i : i + 1, j : j + 1, k : k + 1, l : l + 1] = Eri_GTO_tensor(
                    I, J, K, L
                )




[CGTOClass(R=array([0., 0., 0.]), exps=array([3.42525091]), N_a=np.float64(6.4796648354485855), d_i=array([0.15432897]), total_l=0, l_dim=1, l_projections=array([[0, 0, 0]], dtype=int32), primitives=[GTO(R=array([0., 0., 0.]), exp=np.float64(3.42525091), total_L=0, l_projections=array([[0, 0, 0]], dtype=int32), normalization_constants=array([1.79444183]), charge=1)]), CGTOClass(R=array([0. , 0. , 1.4]), exps=array([3.42525091]), N_a=np.float64(6.4796648354485855), d_i=array([0.15432897]), total_l=0, l_dim=1, l_projections=array([[0, 0, 0]], dtype=int32), primitives=[GTO(R=array([0. , 0. , 1.4]), exp=np.float64(3.42525091), total_L=0, l_projections=array([[0, 0, 0]], dtype=int32), normalization_constants=array([1.79444183]), charge=1)]), CGTOClass(R=array([2.1, 0. , 0. ]), exps=array([3.42525091]), N_a=np.float64(6.4796648354485855), d_i=array([0.15432897]), total_l=0, l_dim=1, l_projections=array([[0, 0, 0]], dtype=int32), primitives=[GTO(R=array([2.1, 0. , 0. ]), exp=np.float64(3.4252

In [11]:
np.allclose(ref_eri, full_ao)

True