# ERI integral evaluation: some tests

In [1]:
from numpy.typing import NDArray
import numpy as np 
from py_mods.src.integrals.GTO import generate_angular_momentum_projections
from py_mods.src.integrals.CGTO import create_CGTOClass, S_GTO_mat, T_GTO_mat, Eri_GTO_tensor
from py_mods.src.SCF.plot_utilities import plot_map

In [2]:
#STO3g example:
l =  0
l_tags = ['S', 'P', 'D', 'F', 'G', 'H']
l_projs = len(generate_angular_momentum_projections(l))
print(f"There are {l_projs} l_projs")

r1 = np.array([0.0, 0.0, 0.0])
r2 = np.array([0.0, 0.0, 1.4])
H_exps = np.array([1])
H_coeffs = np.array([1])

# Construct the CGTO 
H_1s_1 = create_CGTOClass(r1, H_exps, H_coeffs, l)
H_1s_2 = create_CGTOClass(r2, H_exps, H_coeffs, l)
H_1p_1 = create_CGTOClass(r1, H_exps, H_coeffs, l+1)
H_1p_2 = create_CGTOClass(r2, H_exps, H_coeffs, l+1)

There are 1 l_projs


In [3]:
print(repr(H_1s_1))
print('\n\n\n')
print(repr(H_1p_1))

CGTOClass(R=array([0., 0., 0.]), exps=array([1]), N_a=np.float64(1.0000000000000002), d_i=array([1]), total_l=0, l_dim=1, l_projections=array([[0, 0, 0]], dtype=int32), primitives=[GTO(R=array([0., 0., 0.]), exp=np.int64(1), total_L=0, l_projections=array([[0, 0, 0]], dtype=int32), normalization_constants=array([0.71270547]), charge=1)])




CGTOClass(R=array([0., 0., 0.]), exps=array([1]), N_a=np.float64(1.0000000000000002), d_i=array([1]), total_l=1, l_dim=3, l_projections=array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32), primitives=[GTO(R=array([0., 0., 0.]), exp=np.int64(1), total_L=1, l_projections=array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32), normalization_constants=array([1.42541094, 1.42541094, 1.42541094]), charge=1)])


In [4]:
Eri_test = Eri_GTO_tensor(H_1s_1, H_1s_1, H_1s_2, H_1s_2)
print(repr(Eri_test))

array([[[[0.68020366]]]])


In [5]:
print(repr(Eri_test))

array([[[[0.68020366]]]])


In [6]:
Eri_test = Eri_GTO_tensor(H_1p_1, H_1s_1, H_1s_2, H_1s_2)
print(repr(Eri_test))

array([[[[0.        ]]],


       [[[0.        ]]],


       [[[0.18616498]]]])
